version: "3"
services:
  nacos:
    image: xxx/nacos-server:v2.3.2
    restart: on-failure
    container_name: nacos
    network_mode: host
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - DB_HOST=192.168.1.1
      - DB_PORT=3307
      - DB_SCHEMA=nacos_server
      - DB_USER=root
      - DB_PASSWORD=root